# the following values must be set in https://travis-ci.com/<github-repo>/settings
# - DOCKER_REPO (eg. myrepo/myapp)
# - DOCKER_USERNAME
# - DOCKER_PASSWORD

services: docker
language: go

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/

env:
  - ARCH=amd64
  - ARCH=arm
  - ARCH=arm64

install:
  - go get github.com/estesp/manifest-tool

before_script:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

script:
  - make ${ARCH} DOCKER_REPO=${DOCKER_REPO}

after_success:
  # optionally deploy only when a new git tag is pushed
  # - if [[ ${TRAVIS_TAG} =~ ^v[0-9]+\.[0-9]+\.[0-9]+.*$ ]] ; then echo deploying tag ${TRAVIS_TAG} ; else exit 0 ; fi
  - make push-${ARCH} DOCKER_REPO=${DOCKER_REPO}
  - make manifest DOCKER_REPO=${DOCKER_REPO}