# the following values must be set in https://travis-ci.com/<github-repo>/settings
# - DOCKER_REPO (eg. myrepo/myapp)
# - DOCKER_USERNAME
# - DOCKER_PASSWORD

services: docker

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/

before_install:
  - mkdir -p ${HOME}/.docker
  - echo '{"experimental":"enabled"}' | tee ${HOME}/.docker/config.json # needed to use docker manifest
  - sudo service docker restart

install:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  - make all DOCKER_REPO=${DOCKER_REPO}

after_success:
  # - if [[ ${TRAVIS_TAG} =~ ^v[0-9]+\.[0-9]+\.[0-9]+.*$ ]] ; then echo deploying tag ${TRAVIS_TAG} ; else exit 0 ; fi
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - make push DOCKER_REPO=${DOCKER_REPO}